package com.garyzhangscm.cwms.inventory.model;

public enum InventoryActivityType {
    INVENTORY_MOVEMENT,
    RECEIVING,
    REVERSE_RECEIVING,
    WORK_ORDER_PRODUCING,
    WORK_ORDER_CONSUME,
    WORK_ORDER_RETURN_MATERIAL,
    PICKING,
    UNPICKING,
    COUNT,
    CYCLE_COUNT,
    AUDIT_COUNT,
    INVENTORY_ADJUSTMENT,
    SPLIT_FOR_INVENTORY_ADJUSTMENT,
    INVENTORY_CONSOLIDATION,
    INVENTORY_SPLIT,
    RELABEL_LPN,
    INVENTORY_STATUS_CHANGE,
    INVENTORY_PACKAGE_TYPE_CHANGE,
    REVERSE_PRODUCTION,
    REVERSE_BY_PRODUCT
}
