/**
 * Copyright 2018
 *
 * @author gzhang
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.garyzhangscm.cwms.inventory.model;


import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.commons.lang.StringUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@Entity
@Table(name = "inventory_configuration")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InventoryConfiguration extends AuditibleEntity<String> implements Serializable {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "inventory_configuration_id")
    @JsonProperty(value="id")
    private Long id;


    @Column(name = "company_id")
    private Long companyId;

    @Transient
    private Company company;

    @Column(name = "warehouse_id")
    private Long warehouseId;

    @Transient
    private Warehouse warehouse;

    @Column(name = "lpn_validation_rule")
    private String lpnValidationRule;

    @Column(name = "new_item_auto_generate_default_package_type")
    private Boolean newItemAutoGenerateDefaultPackageType = true;

    @Column(name = "new_item_default_package_type_name")
    private String newItemDefaultPackageTypeName;
    @Column(name = "new_item_default_package_type_description")
    private String newItemDefaultPackageTypeDescription;

    // we will display some meaningful name in web / mobile device
    @Column(name = "inventory_attribute_1_display_name")
    private String inventoryAttribute1DisplayName;
    @Column(name = "inventory_attribute_1_enabled")
    private Boolean inventoryAttribute1Enabled;
    @Column(name = "inventory_attribute_2_display_name")
    private String inventoryAttribute2DisplayName;
    @Column(name = "inventory_attribute_2_enabled")
    private Boolean inventoryAttribute2Enabled;
    @Column(name = "inventory_attribute_3_display_name")
    private String inventoryAttribute3DisplayName;
    @Column(name = "inventory_attribute_3_enabled")
    private Boolean inventoryAttribute3Enabled;
    @Column(name = "inventory_attribute_4_display_name")
    private String inventoryAttribute4DisplayName;
    @Column(name = "inventory_attribute_4_enabled")
    private Boolean inventoryAttribute4Enabled;
    @Column(name = "inventory_attribute_5_display_name")
    private String inventoryAttribute5DisplayName;
    @Column(name = "inventory_attribute_5_enabled")
    private Boolean inventoryAttribute5Enabled;



    @OneToMany(
            mappedBy = "inventoryConfiguration",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.EAGER
    )
    private List<ItemDefaultPackageUOM> itemDefaultPackageUOMS= new ArrayList<>();


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Long getWarehouseId() {
        return warehouseId;
    }

    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    public Warehouse getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

    public String getLpnValidationRule() {
        return lpnValidationRule;
    }

    public void setLpnValidationRule(String lpnValidationRule) {
        this.lpnValidationRule = lpnValidationRule;
    }

    public Boolean getNewItemAutoGenerateDefaultPackageType() {
        return newItemAutoGenerateDefaultPackageType;
    }

    public void setNewItemAutoGenerateDefaultPackageType(Boolean newItemAutoGenerateDefaultPackageType) {
        this.newItemAutoGenerateDefaultPackageType = newItemAutoGenerateDefaultPackageType;
    }

    public String getNewItemDefaultPackageTypeName() {
        return newItemDefaultPackageTypeName;
    }

    public void setNewItemDefaultPackageTypeName(String newItemDefaultPackageTypeName) {
        this.newItemDefaultPackageTypeName = newItemDefaultPackageTypeName;
    }

    public String getNewItemDefaultPackageTypeDescription() {
        return newItemDefaultPackageTypeDescription;
    }

    public void setNewItemDefaultPackageTypeDescription(String newItemDefaultPackageTypeDescription) {
        this.newItemDefaultPackageTypeDescription = newItemDefaultPackageTypeDescription;
    }

    public List<ItemDefaultPackageUOM> getItemDefaultPackageUOMS() {
        return itemDefaultPackageUOMS;
    }

    public void setItemDefaultPackageUOMS(List<ItemDefaultPackageUOM> itemDefaultPackageUOMS) {
        this.itemDefaultPackageUOMS = itemDefaultPackageUOMS;
    }

    public String getInventoryAttribute1DisplayName() {
        return inventoryAttribute1DisplayName;
    }

    public void setInventoryAttribute1DisplayName(String inventoryAttribute1DisplayName) {
        this.inventoryAttribute1DisplayName = inventoryAttribute1DisplayName;
    }

    public String getInventoryAttribute2DisplayName() {
        return inventoryAttribute2DisplayName;
    }

    public void setInventoryAttribute2DisplayName(String inventoryAttribute2DisplayName) {
        this.inventoryAttribute2DisplayName = inventoryAttribute2DisplayName;
    }

    public String getInventoryAttribute3DisplayName() {
        return inventoryAttribute3DisplayName;
    }

    public void setInventoryAttribute3DisplayName(String inventoryAttribute3DisplayName) {
        this.inventoryAttribute3DisplayName = inventoryAttribute3DisplayName;
    }

    public String getInventoryAttribute4DisplayName() {
        return inventoryAttribute4DisplayName;
    }

    public void setInventoryAttribute4DisplayName(String inventoryAttribute4DisplayName) {
        this.inventoryAttribute4DisplayName = inventoryAttribute4DisplayName;
    }

    public String getInventoryAttribute5DisplayName() {
        return inventoryAttribute5DisplayName;
    }

    public void setInventoryAttribute5DisplayName(String inventoryAttribute5DisplayName) {
        this.inventoryAttribute5DisplayName = inventoryAttribute5DisplayName;
    }

    public Boolean getInventoryAttribute1Enabled() {
        return inventoryAttribute1Enabled;
    }

    public void setInventoryAttribute1Enabled(Boolean inventoryAttribute1Enabled) {
        this.inventoryAttribute1Enabled = inventoryAttribute1Enabled;
    }

    public Boolean getInventoryAttribute2Enabled() {
        return inventoryAttribute2Enabled;
    }

    public void setInventoryAttribute2Enabled(Boolean inventoryAttribute2Enabled) {
        this.inventoryAttribute2Enabled = inventoryAttribute2Enabled;
    }

    public Boolean getInventoryAttribute3Enabled() {
        return inventoryAttribute3Enabled;
    }

    public void setInventoryAttribute3Enabled(Boolean inventoryAttribute3Enabled) {
        this.inventoryAttribute3Enabled = inventoryAttribute3Enabled;
    }

    public Boolean getInventoryAttribute4Enabled() {
        return inventoryAttribute4Enabled;
    }

    public void setInventoryAttribute4Enabled(Boolean inventoryAttribute4Enabled) {
        this.inventoryAttribute4Enabled = inventoryAttribute4Enabled;
    }

    public Boolean getInventoryAttribute5Enabled() {
        return inventoryAttribute5Enabled;
    }

    public void setInventoryAttribute5Enabled(Boolean inventoryAttribute5Enabled) {
        this.inventoryAttribute5Enabled = inventoryAttribute5Enabled;
    }
}
