package com.garyzhangscm.cwms.inventory.model;

public enum InventoryConfigurationType {
    LPN_VALIDATION_RULE,
    NEW_ITEM_AUTO_GENERATE_DEFAULT_PACKAGE,
    NEW_ITEM_DEFAULT_PACKAGE_UOM,
    NEW_ITEM_DEFAULT_PACKAGE_UOM_QUANTITY,
    NEW_ITEM_DEFAULT_PACKAGE_UOM_WEIGHT,
    NEW_ITEM_DEFAULT_PACKAGE_UOM_LENGTH,
    NEW_ITEM_DEFAULT_PACKAGE_UOM_WIDTH,
    NEW_ITEM_DEFAULT_PACKAGE_UOM_HEIGHT
}
