package com.garyzhangscm.cwms.outbound.model;

public enum AllocationStrategyType {
    FIRST_IN_FIRST_OUT,
    FIRST_EXPIRED_FIRST_OUT,
    EMPTY_LOCATION,
    LESS_LOCATION,
    CONFIGURATION,
    CONFIGURATION_WITH_FIRST_IN_FIRST_OUT,
    CONFIGURATION_WITH_FIRST_EXPIRED_FIRST_OUT,
    CONFIGURATION_EMPTY_LOCATION,
    CONFIGURATION_LESS_LOCATION
}
