package com.garyzhangscm.cwms.outbound.model;

public enum IntegrationType {
    SYSTEM_ERROR,
    INTEGRATION_CUSTOMER,
    INTEGRATION_CLIENT,
    INTEGRATION_SUPPLIER,
    INTEGRATION_ITEM,
    INTEGRATION_ITEM_FAMILY,
    INTEGRATION_ITEM_PACKAGE_TYPE,
    INTEGRATION_ITEM_UNIT_OF_MEASURE,
    INTEGRATION_ORDER,
    INTEGRATION_ORDER_LINE,
    INTEGRATION_RECEIPT,
    INTEGRATION_RECEIPT_LINE,
    INTEGRATION_ORDER_CONFIRMATION,
    INTEGRATION_ORDER_LINE_CONFIRMATION,
    INTEGRATION_SHIPMENT_LINE_CONFIRMATION,
    INTEGRATION_RECEIPT_CONFIRMATION,
    INTEGRATION_RECEIPT_LINE_CONFIRMATION,
    INTEGRATION_INVENTORY_ADJUSTMENT_CONFIRMATION,
    INTEGRATION_INVENTORY_SHIPPING_CONFIRMATION,
    INTEGRATION_INVENTORY_ATTRIBUTE_CHANGE_CONFIRMATION,
    INTEGRATION_WORK_ORDER,
    INTEGRATION_BILL_OF_MATERIAL

}
