package com.garyzhangscm.cwms.outbound.model;

public enum OrderActivityType {
    ORDER_PLAN,
    ORDER_ALLOCATION,
    PICK_CALCELLATION,
    SHIPMENT_LINE_CANCELLATION,
    SHIPMENT_CANCELLATION,
    SHIPMENT_STAGE,
    SHIPMENT_LOADING,
    SHIPMENT_DISPATCH,
    ORDER_COMPLETE,
    SHIPMENT_ALLOCATION,
    ORDER_CANCELLATION,
    PICK_CONFIRM,
    SHORT_ALLOCATION_CANCELLATION,
    SHORT_ALLOCATION_ALLOCATE,
    ORDER_CREATE,
    BULK_PICK_CONFIRM,
    LIST_PICK_CONFIRM
}
