package com.garyzhangscm.cwms.adminserver.model;

public enum BillableCategory {
    STORAGE_FEE_BY_NET_VOLUME,
    STORAGE_FEE_BY_GROSS_VOLUME,
    STORAGE_FEE_BY_LOCATION_COUNT,
    STORAGE_FEE_BY_PALLET_COUNT,
    HANDLING_FEE,
    ADDON_FEE,
    TRANSACTIONS,
    RECEIPT_LINE_PROCESS_FEE,
    RECEIPT_PROCESS_FEE,
    RECEIVING_CHARGE_BY_QUANTITY,
    RECEIVING_CHARGE_BY_VOLUME,
    ORDER_LINE_PROCESS_FEE,
    ORDER_PROCESS_FEE ,
    SHIPPING_CHARGE_BY_QUANTITY,
    SHIPPING_CHARGE_BY_VOLUME,
    OTHERS,
    STORAGE_FEE_BY_AGING_PALLET;
}
