version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    # container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#    networks:
#      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    # container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
#    networks:
#      - elastic


# Setup Volumes for data
# All elastic search 's data will be saved on the local volume
# which is maintained by docker
volumes:
  data01:
    driver: local
  data02:
    driver: local

# networks:
#  elastic:
#    driver: bridge