package com.garyzhangscm.cwms.integration.model;

public enum AlertType {
    INTEGRATION_FAIL,
    INTEGRATION_SUCCESS,
    ORDER_COMPLETE,
    INVENTORY_STATUS_CHANGE,
    INVENTORY_ADJUSTMENT,
    RECEIPT_COMPLETE,
    INTEGRATION_TO_HOST_SUCCESS,
    INTEGRATION_TO_HOST_FAIL,
    NEW_ORDER,
    NEW_WORK_ORDER,
    NEW_RECEIPT,
    MODIFY_ORDER,
    MODIFY_WORK_ORDER,
    MODIFY_RECEIPT,
    NEW_ITEM,
    MODIFY_ITEM,
    REQUEST_ORDER_CANCELLATION,
    CANCEL_ORDER
}
