package com.garyzhangscm.cwms.integration.model;

public enum AlertType {
    INTEGRATION_FAIL,
    INTEGRATION_SUCCESS,
    ORDER_COMPLETE,
    INVENTORY_STATUS_CHANGE,
    INVENTORY_ADJUSTMENT,
    RECEIPT_COMPLETE,
    INTEGRATION_TO_HOST_SUCCESS,
    INTEGRATION_TO_HOST_FAIL
}
