/**
 * Copyright 2019
 *
 * @author gzhang
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.garyzhangscm.cwms.adminserver.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.garyzhangscm.cwms.adminserver.clients.*;
import com.garyzhangscm.cwms.adminserver.exception.ResourceNotFoundException;
import com.garyzhangscm.cwms.adminserver.exception.SystemFatalException;
import com.garyzhangscm.cwms.adminserver.model.DataInitialRequest;
import com.garyzhangscm.cwms.adminserver.model.DataInitialRequestStatus;
import com.garyzhangscm.cwms.adminserver.model.User;
import com.garyzhangscm.cwms.adminserver.model.tester.TestScenarioSuit;
import com.garyzhangscm.cwms.adminserver.model.wms.*;
import com.garyzhangscm.cwms.adminserver.repository.DataInitialRequestRepository;
import org.apache.commons.lang.StringUtils;
import org.apache.logging.log4j.util.Strings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.*;

@Service
public class DataService {

    private static final Logger logger = LoggerFactory.getLogger(DataService.class);

    @Autowired
    private WarehouseLayoutServiceRestemplateClient warehouseLayoutServiceRestemplateClient;
    @Autowired
    private ResourceServiceRestemplateClient resourceServiceRestemplateClient;
    @Autowired
    private CommonServiceRestemplateClient commonServiceRestemplateClient;
    @Autowired
    private InventoryServiceRestemplateClient inventoryServiceRestemplateClient;
    @Autowired
    private InboundServiceRestemplateClient inboundServiceRestemplateClient;

    @Autowired
    private DataInitialRequestRepository dataInitialRequestRepository;


    // Map of all inprocess data initiate request
    // key: request id(database primary key)
    // value: request
    private Map<Long, DataInitialRequest> dataInitialRequestMap = new HashMap<>();

    /**
     * Initiate production data, the user will specify the
     * company name , warehouse name and admin user name, we will
     * create some default data so the user can login and create
     * more data.
     * @param companyName company name
     * @param warehouseName warehouse name
     * @param adminUsername admin user name
     */
    public void initiateProductionData(String companyName,
                                       String warehouseName,
                                       String adminUsername,
                                       String requestUsername) throws JsonProcessingException {

        if (!validateUserForInitiateProductionData(requestUsername)) {
            throw SystemFatalException.raiseException("user " + requestUsername + " can't initiate the company data");
        }
        DataInitialRequest dataInitialRequest = new DataInitialRequest(
                companyName, warehouseName, adminUsername, requestUsername
        );
        dataInitialRequest.setStatus(DataInitialRequestStatus.INITIATING);

        dataInitialRequest = dataInitialRequestRepository.save(dataInitialRequest);
        long dataInitialRequestId = dataInitialRequest.getId();
        dataInitialRequestMap.put(dataInitialRequestId, dataInitialRequest);

        new Thread(() ->{

            DataInitialRequest savedDataInitialRequest =
                    dataInitialRequestMap.get(dataInitialRequestId);

            try {
                Company company  = initiateCompany(companyName);
                // we will save the company code that generated by the system here
                // as the user will need to have company code in order to login
                savedDataInitialRequest.setCompanyCode(company.getCode());
                
                Warehouse warehouse = initiateWarehouse(company, warehouseName);

                initiateSystemControllerNumber(warehouse);

                List<UnitOfMeasure> unitOfMeasures = initiateUnitOfMeasure(warehouse);
                // start to create sample location group and locations in this warehouse
                initiateStorageLocations(warehouse, unitOfMeasures);

                initiateUser(company, adminUsername);
                
                
                savedDataInitialRequest.setStatus(DataInitialRequestStatus.COMPLETE);
                dataInitialRequestRepository.save(savedDataInitialRequest);
                dataInitialRequestMap.remove(dataInitialRequestId);

            } catch (Exception e) {
                e.printStackTrace();
                savedDataInitialRequest.setStatus(DataInitialRequestStatus.FAIL);
                dataInitialRequestRepository.save(savedDataInitialRequest);
                dataInitialRequestMap.remove(dataInitialRequestId);
            }
        }).start();

    }

    private void initiateSystemControllerNumber(Warehouse warehouse) throws JsonProcessingException {
        // initial system controlled number
        // # variable / prefix / length / current number / rollover
        // 1. allocation-transaction-history-group-id / ATHG / 10 / 0 / true
        // 2. allocation-transaction-history-number	/ ATH  / 10 / 0 / true
        // 3. bill-of-material	/ BOM / 10 / 0 / true
        // 4. billing-request-number / BR / 10 / 0 / true
        // 5. cancelled-pick-number / CPK / 10 / 0 / true
        // 6. cartonization-number / CTN / 10 / 0 / true
        // 7. csr-order-number	/ CSR / 10 / 0 / true
        // 8. cycle-count-batch-id / CB / 10 / 0 / true
        // 9. inventory-activity-transaction-group-id / INVACTGRP / 10 / 0 / true
        // 10. inventory-activity-transaction-id / INVACT / 10 / 0 / true
        // 11. inventory-snapshot-batch-number / INVSNAP / 10 / 0 / true
        // 12. invoice-number	/ INVOICE / 10 / 0 / true
        // 13. item-sampling-number	/ IS / 10 / 0 / true
        // 14. list-pick / LPICK / 10 / 0 / true
        // 15. location-utilization-snapshot-number	/ LUS / 10 / 0 / true
        // 16. lpn / L / 10 / 0 / true
        // 17. mps-number	/ MPS / 10 / 0 / true
        // 18. mrp-number	/ MRP / 10 / 0 / true
        // 19. order-activity-number	/ OA / 10 / 0 / true
        // 20. order-activity-transaction-group-id	/ OAG / 10 / 0 / true
        // 21. order-number / CT / 10 / 0 / false
        // 22. pick-number / PICK / 10 / 0 / true
        // 23. production-plan / PRP / 10 / 0 / true
        // 24. qc-inspection-request	/ QCR / 10 / 0 / true
        // 25. receipt-number / RECPT / 10 / 0 / true
        // 26. receiving-lpn-number	/ R1 / 10 / 0 / true
        // 27. shipment-line-number / SL / 10 / 0 / true
        // 28. shipment-number / SHIP / 10 / 0 / true
        // 29. shipping-cartonization-number / SCTN	 / 10 / 0 / true
        // 30. stop / STP / 10 / 0 / true
        // 31. trailer-appointment-number	/ TAP / 10 / 0 / true
        // 32. wave-number / WAV / 10 / 0 / true
        // 33. work-order-lpn-number	/ W1 / 10 / 0 / true
        // 34. work-order-number / WO / 10 / 0 / true
        // 35. work-order-qc-sample-number	/ WQC / 10 / 0 / true
        // 36. work-task / WORK / 10 / 0 / true


        SystemControlledNumber[] systemControlledNumbers =
                getPredefinedSystemControllerNumber(warehouse.getId());
        for (SystemControlledNumber systemControlledNumber : systemControlledNumbers) {
            logger.debug("Start to init system controlled number: {}",
                    systemControlledNumber);
            SystemControlledNumber newSystemControlledNumber =
                    commonServiceRestemplateClient.addSystemControlledNumbers(
                            systemControlledNumber
                    );

            logger.debug("system controller number {} initialed with id {}",
                    newSystemControlledNumber.getVariable(),
                    newSystemControlledNumber.getId());

        }


    }

    public SystemControlledNumber[] getPredefinedSystemControllerNumber(Long warehouseId) {
        return new SystemControlledNumber[]{
                new SystemControlledNumber(warehouseId, "allocation-transaction-history-group-id",
                        "ATHG", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "allocation-transaction-history-number",
                        "ATH", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "bill-of-material",
                        "BOM", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "billing-request-number",
                        "BR", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "cancelled-pick-number",
                        "CPK", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "cartonization-number",
                        "CTN", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "csr-order-number",
                        "CSR", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "cycle-count-batch-id",
                        "CB", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "inventory-activity-transaction-group-id",
                        "INVACTGRP", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "inventory-activity-transaction-id",
                        "INVACT", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "invoice-number",
                        "INVOICE", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "item-sampling-number",
                        "IS", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "list-pick",
                        "LPICK", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "location-utilization-snapshot-number",
                        "LUS", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "lpn",
                        "L", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "mps-number",
                        "MPS", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "mrp-number",
                        "MRP", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "order-activity-number",
                        "OA", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "order-activity-transaction-group-id",
                        "OAG", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "order-number",
                        "ORDER", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "pick-number",
                        "PICK", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "production-plan",
                        "PRP", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "qc-inspection-request",
                        "QCR", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "receipt-number",
                        "RECPT", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "receiving-lpn-number",
                        "R1", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "shipment-line-number",
                        "SL", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "shipment-number",
                        "SHIP", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "shipping-cartonization-number",
                        "SCTN", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "stop",
                        "STP", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "trailer-appointment-number",
                        "TAP", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "wave-number",
                        "WAV", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "work-order-lpn-number",
                        "W1", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "work-order-number",
                        "WO", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "work-order-qc-sample-number",
                        "WQC", "", 10, 0, true),
                new SystemControlledNumber(warehouseId, "work-task",
                        "WORK", "", 10, 0, true)
        };
    }

    private void initiateUser(Company company, String adminUsername) throws JsonProcessingException {
        // create a admin user with both the username and password
        // equals to the adminUsername which specified by the user
        User user = new User(company.getId(),
                adminUsername, adminUsername, adminUsername,
                true, adminUsername, adminUsername, "");

        logger.debug("Start to create user {}", adminUsername);
        user = resourceServiceRestemplateClient.createUser(user);
        logger.debug("User created, id {}", user.getId());


    }

    /**
     * Initial default unit of measure:
     * 1. EA: Each
     * 2. CS: Case
     * 3. PL: Pallet
     * @param warehouse
     * @return
     */
    private List<UnitOfMeasure> initiateUnitOfMeasure(Warehouse warehouse) throws JsonProcessingException {
        List<UnitOfMeasure> unitOfMeasures = new ArrayList<>();

        UnitOfMeasure each = new UnitOfMeasure(warehouse.getId(), "EA", "Each");
        each = commonServiceRestemplateClient.createUnitOfMeasure(each);
        logger.debug("each UOM created! id: {}",
                each.getId());

        UnitOfMeasure caseUom = new UnitOfMeasure(warehouse.getId(), "CS", "Case");
        caseUom = commonServiceRestemplateClient.createUnitOfMeasure(caseUom);
        logger.debug("case UOM created! id: {}",
                caseUom.getId());

        UnitOfMeasure pallet = new UnitOfMeasure(warehouse.getId(), "PL", "Pallet");
        pallet = commonServiceRestemplateClient.createUnitOfMeasure(pallet);
        logger.debug("pallet UOM created! id: {}",
                pallet.getId());

        unitOfMeasures.add(each);
        unitOfMeasures.add(caseUom);
        unitOfMeasures.add(pallet);
        return  unitOfMeasures;
    }

    private void initiateStorageLocations(Warehouse warehouse, List<UnitOfMeasure> unitOfMeasures) throws JsonProcessingException {

        // default the location group name to STORAGE
        // and locations to STORAGE-001 to STORAGE-010
        String locationGroupName = "STORAGE";
        // start to create location group under storage type
        List<LocationGroupType> storageLocationGroupTypes =
                warehouseLayoutServiceRestemplateClient.getStorageLocationTypes();
        // we should only have one and only one storage location type
        if (storageLocationGroupTypes.size() == 0) {
            throw SystemFatalException.raiseException("Can't find a storage location group type, fail to create locations");
        }
        LocationGroupType storageLocationGroupType = storageLocationGroupTypes.get(0);

        LocationGroup storageLocationGroup = initiateLocationGroup(
                warehouse, storageLocationGroupType, locationGroupName, unitOfMeasures);

        for(int i = 0; i < 30; i++) {
            String locationName = locationGroupName + String.format("%03d", (i + 1));
            initiateLocation(warehouse, storageLocationGroup, locationName, (i + 1));
        }
        initiatePutawayConfiguration(warehouse, storageLocationGroup);



    }

    private void initiatePutawayConfiguration(
            Warehouse warehouse, LocationGroup storageLocationGroup) {
        // we will setup default putaway configuration so everything will
        // go into the storage areas
        logger.debug("Start setup putaway configuration");

        InventoryStatus availableInventoryStatus =
                inventoryServiceRestemplateClient.getInventoryStatusByName(
                        warehouse.getId(),
                        "AVAL"
                );

        logger.debug("find available inventory status : {}",
                Objects.nonNull(availableInventoryStatus));

        // we don't have the available inventory status defined. we will do nothing
        if (Objects.isNull(availableInventoryStatus)) {
            return;
        }

        PutawayConfiguration putawayConfiguration =
                    new PutawayConfiguration(
                            1,
                            warehouse.getId(),
                            null, // criteria: item
                            null, // criteria: item family
                            availableInventoryStatus.getId(),
                            null, // destination： location
                            storageLocationGroup.getId() , // destination: location group
                            null , // destination:  location group type
                            PutawayConfigurationStrategy.EMPTY_LOCATIONS.toString()
                    );

        try {
            logger.debug("Will save putaway configuration: \n {}", putawayConfiguration);
            inboundServiceRestemplateClient.addPutawayConfiguration(putawayConfiguration);
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
    }

    private void initiateLocation(Warehouse warehouse,
                                  LocationGroup storageLocationGroup,
                                  String locationName,
                                  int sequence) throws JsonProcessingException {
        logger.debug("Start to create location {} in group {}, warehouse {}, with sequence {}",
                locationName, storageLocationGroup.getName(),
                warehouse.getName(),
                sequence);
        Location location = new Location(warehouse, storageLocationGroup,
                locationName, sequence);

        warehouseLayoutServiceRestemplateClient.createLocation(location);

    }

    private LocationGroup initiateLocationGroup(
            Warehouse warehouse, LocationGroupType storageLocationGroupType,
            String locationGroupName, List<UnitOfMeasure> unitOfMeasures) throws JsonProcessingException {
        LocationGroup locationGroup = new LocationGroup(
                warehouse, storageLocationGroupType,
                locationGroupName, locationGroupName
        );
        logger.debug("Start to create location group {} in warehouse {}, location group type {}",
                locationGroupName, warehouse.getName(),
                storageLocationGroupType.getName());

        unitOfMeasures.forEach(
                unitOfMeasure -> locationGroup.addPickableUnitOfMeasure(
                        new PickableUnitOfMeasure(warehouse.getId(), unitOfMeasure.getId())
                )
        );

        return warehouseLayoutServiceRestemplateClient.createLocationGroup(locationGroup);
    }

    public boolean validateUserForInitiateProductionData(String requestUsername) {

        logger.debug("Start to check if user {} can start a data initiation",
                requestUsername);


        return resourceServiceRestemplateClient.validateSystemAdminUser(requestUsername);


    }

    private Warehouse initiateWarehouse(Company company, String warehouseName) throws JsonProcessingException {
        Warehouse warehouse = new Warehouse();
        warehouse.setName(warehouseName);
        warehouse.setSize(0.0);
        warehouse.setAddressCountry(company.getAddressCountry());
        warehouse.setAddressState(company.getAddressState());
        warehouse.setAddressCounty(company.getAddressCounty());
        warehouse.setAddressCity(company.getAddressCity());
        warehouse.setAddressLine1(company.getAddressLine1());
        warehouse.setAddressPostcode(company.getAddressPostcode());

        return warehouseLayoutServiceRestemplateClient.createWarehouse(
                company.getId(), warehouse);


    }

    private Company initiateCompany(String companyName) throws JsonProcessingException {

        Company company = new Company();
        company.setCode(getNextCompanyCode());
        company.setName(companyName);
        company.setDescription(companyName);

        // fake address(white house)
        company.setContactorFirstname("Default");
        company.setContactorLastname("Default");
        company.setAddressCountry("USA");
        company.setAddressState("Washington");
        company.setAddressCounty("Washington");
        company.setAddressCity("Washington");
        company.setAddressLine1("1600 Pennsylvania Avenue NW");
        company.setAddressPostcode("20502");


        return warehouseLayoutServiceRestemplateClient.createCompany(company);


    }

    private String getNextCompanyCode() {
        return warehouseLayoutServiceRestemplateClient.getNextCompanyCode();
    }


    public List<DataInitialRequest> findInitiateProductionData(String companyName) {
        return dataInitialRequestRepository.findAll(
                (Root<DataInitialRequest> root, CriteriaQuery<?> criteriaQuery, CriteriaBuilder criteriaBuilder) -> {
                    List<Predicate> predicates = new ArrayList<Predicate>();


                    if (StringUtils.isNotBlank(companyName)) {
                        predicates.add(criteriaBuilder.equal(root.get("companyName"), companyName));
                    }
                    Predicate[] p = new Predicate[predicates.size()];
                    return criteriaBuilder.and(predicates.toArray(p));
                }
        );
    }

    public DataInitialRequest findInitiateProductionDataById(Long id) {
        return dataInitialRequestRepository.findById(id)
                .orElseThrow(() -> ResourceNotFoundException.raiseException("data initial request not found by id: " + id));
    }


    /**
     * Export data from the server so we can import into another server
     * @param companyId
     */
    public void exportProductionData(Long companyId){


    }

    public void initSystemControllerNumber() {
        // let's first get all the companies and warehouse defined in the system
        List<Company> companies = warehouseLayoutServiceRestemplateClient.getAllCompanies();
        List<Warehouse> warehouses = new ArrayList<>();
        companies.forEach(
                company -> {
                    List<Warehouse> companyWarehouses = warehouseLayoutServiceRestemplateClient.getWarehouseByCompany(
                            company.getId()
                    );
                    warehouses.addAll(companyWarehouses);
                }
        );
        logger.debug("we get {} warehouses out of {} companies",
                warehouses.size(), companies.size());
        warehouses.forEach(
                warehouse -> {
                    SystemControlledNumber[] systemControlledNumbers =
                            getPredefinedSystemControllerNumber(warehouse.getId());
                    for (SystemControlledNumber systemControlledNumber : systemControlledNumbers) {
                        logger.debug("let's check if the system controller number: {} is defined for warehouse {}",
                                systemControlledNumber.getVariable(), warehouse.getName());
                        String nextNumber =
                                commonServiceRestemplateClient.getNextNumber(warehouse.getId(),
                                        systemControlledNumber.getVariable()
                                );

                        logger.debug("system controller number: {} for warehouse {}, value? {}",
                                systemControlledNumber.getVariable(),
                                warehouse.getName(), nextNumber);
                        if (Strings.isBlank(nextNumber)) {

                            logger.debug("ERROR!!! system controller number: {} is NOT defined for warehouse {}",
                                    systemControlledNumber.getVariable(), warehouse.getName());
                            try {
                                        commonServiceRestemplateClient.addSystemControlledNumbers(
                                                systemControlledNumber
                                        );
                            } catch (JsonProcessingException e) {
                                e.printStackTrace();
                            }

                        }

                    }
                }
        );

    }
}
