# ==============================================================
# = Data Source
# ==============================================================
spring:
  datasource:
     # url: jdbc:mysql://192.168.99.100:3306/cwms
     url: jdbc:mysql://192.168.99.100:3306/cwms
     driverClassName: com.mysql.cj.jdbc.Driver
     username: cwms
     password: "{cipher}a53f0b89e7c3a118264c975185ca6a942c9466f7b20911220c034a3c236c69fe"
     initialization-mode: always
  # ==============================================================
  # = Keep the connection alive if idle for a long time (needed in production)
  # ==============================================================
      testWhileIdle: true
      validationQuery: SELECT 1

  # ==============================================================
  # = Show or not log for each sql query
  # ==============================================================
  jpa:
      show-sql: true
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect
              enable_lazy_load_no_trans: true
  # ==============================================================
  # = Hibernate ddl auto (create, create-drop, update)
  # ==============================================================
  hibernate:
      ddl-auto: none
  # ==============================================================
  # = For actuator
  # ==============================================================
  # Endpoint IDs that should be included or '*' for all., default is health and info
  # management.endpoints.web.exposure.include=health,info
# management:
#  endpoints:
#      web:
#          exposure:
#              include:*
# Endpoint IDs that should be excluded or '*' for all.
# management.endpoints.web.exposure.exclude=

# Base path for Web endpoints. Relative to server.servlet.context-path or management.server.servlet.context-path if management.server.port is configured.
# management.endpoints.web.base-path=/actuator

# Mapping between endpoint IDs and the path that should expose them.
# management.endpoints.web.path-mapping=

####    Securing Endpoint
# Roles used to determine whether or not a user is authorized to be shown details. When empty, all authenticated users are authorized. //for health
# management.endpoint.health.roles=

# When to show full health details.
# management.endpoint.health.show-details=always,never

#### Enable or Disable endpoint
# Whether to enable the health endpoint.
# e.g. management.endpoint.health.enabled=true
# management.endpoint.(endpointName).enabled=true
