version: '3'
services:
  ######################################
  # 4. auth(OAuth2 server)
  #####################################
  authserver:
      image: garyzhangscm/cwms-auth
      ports:
          - "8901:8901"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true

  layoutservice:
      image: garyzhangscm/cwms-layoutserver
      ports:
          - "8180:8180"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
         co.elastic.logs/enabled: true

  resourceservice:
      image: garyzhangscm/cwms-ressvr
      ports:
          - "8280:8280"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
           co.elastic.logs/enabled: true

  commonservice:
      image: garyzhangscm/cwms-commonserver
      ports:
          - "8380:8380"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true

  inventoryservice:
      image: garyzhangscm/cwms-inventoryserver
      ports:
          - "8480:8480"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true

  inboundservice:
      image: garyzhangscm/cwms-inboundserver
      ports:
          - "8580:8580"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true

  outboundservice:
      image: garyzhangscm/cwms-outboundserver
      ports:
          - "8680:8680"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true

  workorderservice:
      image: garyzhangscm/cwms-workorderserver
      ports:
          - "8780:8780"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true

  integrationservice:
      image: garyzhangscm/cwms-integrationserver
      ports:
          - "8880:8880"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true

  adminservice:
      image: garyzhangscm/cwms-adminserver
      ports:
          - "8078:8078"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"
          TZ: "America/Los_Angeles"
          SYSTEM_VERSION: "latest"
      labels:
          co.elastic.logs/enabled: true
#      volumes:
#          - "/etc/localtime:/etc/localtime:ro"
#          - "/etc/timezone:/etc/timezone:ro"

