version: '2'
services:

  layoutservice:
      image: garyzhangscm/cwms-layoutserver
      ports:
          - "8180:8180"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"

  resourceservice:
      image: garyzhangscm/cwms-ressvr
      ports:
          - "8280:8280"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"


  commonservice:
      image: garyzhangscm/cwms-commonserver
      ports:
          - "8380:8380"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"


  inventoryservice:
      image: garyzhangscm/cwms-inventoryserver
      ports:
          - "8480:8480"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"

  inboundservice:
      image: garyzhangscm/cwms-inboundserver
      ports:
          - "8580:8580"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"


  outboundservice:
      image: garyzhangscm/cwms-outboundserver
      ports:
          - "8680:8680"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"


  workorderservice:
      image: garyzhangscm/cwms-workorderserver
      ports:
          - "8780:8780"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"


  integrationservice:
      image: garyzhangscm/cwms-integrationserver
      ports:
          - "8880:8880"
      environment:
          SPRING_PROFILE: "aws-dev"
          CONFIGSERVER_URI: "http://configserver:8888"
          # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
          DATABASE_URL: "database"
          CONFIGSERVER_PORT:   "8888"
          DATABASESERVER_PORT: "3306"
          ENCRYPT_KEY:       "CWMS2018"
          COMPOSE_PROJECT_NAME: "CWMS-APP"