version: '3'
services:
  authserver:
    image: garyzhangscm/cwms-auth
    ports:
      - "8901:8901"
    environment:
      SPRING_PROFILE: "aws-dev"
      CONFIGSERVER_URI: "http://configserver:8888"
      # DATABASE_URL: "cwms.cwboexrsigq2.us-west-1.rds.amazonaws.com"
      DATABASE_URL: "database"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "3306"
      ENCRYPT_KEY:       "CWMS2018"
      COMPOSE_PROJECT_NAME: "CWMS-APP"
    deploy:
      resources:
        limits:
          memory: 500m
