version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 10
      KAFKA_CREATE_TOPICS: "ops_transaction:1:1,order_activity:1:1,test_data_init:1:1,short_allocation:1:1,
                     INTEGRATION_CUSTOMER:1:1,INTEGRATION_CLIENT:1:1,INTEGRATION_SUPPLIER:1:1,
                     INTEGRATION_ITEM:1:1,INTEGRATION_ITEM_FAMILY:1:1,INTEGRATION_ITEM_PACKAGE_TYPE:1:1,INTEGRATION_ITEM_UNIT_OF_MEASURE:1:1,
                     INVENTORY_ACTIVITY:1:1,INVENTORY_ADJUSTMENT_REQUEST_PROCESSED:1:1,INTEGRATION_INVENTORY_ADJUSTMENT_CONFIRMATION:1:1,
                     INTEGRATION_INVENTORY_ATTRIBUTE_CHANGE_CONFIRMATION:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
